//! Gcode emission from planned toolpaths.

use crate::{
    toolpath::{MoveKind, Path},
    SlicerConfig,
};
use glam::DVec3;

/// Substitute `{print_min_x}`, `{print_min_y}`, `{print_max_x}`,
/// `{print_max_y}` placeholders in a Gcode template with the given first-
/// layer XY bounding box, formatted to 3 decimal places (matching the
/// coordinate precision `emit` uses for move lines). Any other `{...}`
/// text in the template (e.g. a Klipper macro's other named parameters
/// like `T_TOOL=240`) is left untouched -- this only recognizes the four
/// bounding-box tokens above.
fn interpolate(template: &str, min_x: f64, min_y: f64, max_x: f64, max_y: f64) -> String {
    template
        .replace("{print_min_x}", &format!("{min_x:.3}"))
        .replace("{print_min_y}", &format!("{min_y:.3}"))
        .replace("{print_max_x}", &format!("{max_x:.3}"))
        .replace("{print_max_y}", &format!("{max_y:.3}"))
}

/// XY bounding box of the first printed layer, identified by the minimum
/// `Segment::order` value across all paths -- robust to non-planar order
/// fields, where Z alone doesn't reliably identify "layer 1" (unlike a
/// flat `Height` field, a curved layer's points don't share one Z value,
/// but every segment sliced from it still shares the same source layer's
/// `order`, copied verbatim by `toolpath::plan`). Returns `None` when
/// `paths` has no segments at all (nothing to bound).
/// Render `config`'s fields as `; key = value` comment lines, one per
/// field, sorted by key for a stable/diffable header -- mirrors the
/// common slicer convention (PrusaSlicer, Cura, etc.) of embedding the
/// full slicing configuration as Gcode comments so a printed part's
/// settings can be recovered from the Gcode file alone. Serializes via
/// `SlicerConfig`'s existing `serde::Serialize` impl (the same one used
/// for saved JSON profiles, see `manifold-gui/src/profile.rs`) rather
/// than hand-listing fields, so newly added config fields are picked up
/// automatically. `start_gcode`/`end_gcode` are omitted: they are
/// (potentially multi-line) Gcode templates already emitted verbatim in
/// the body, so echoing them again as escaped comment text would be
/// redundant noise rather than useful metadata.
fn config_comment_lines(config: &SlicerConfig) -> Vec<String> {
    let value = serde_json::to_value(config).expect("SlicerConfig always serializes to JSON");
    let Some(fields) = value.as_object() else {
        return Vec::new();
    };
    let mut lines: Vec<String> = fields
        .iter()
        .filter(|(key, _)| key.as_str() != "start_gcode" && key.as_str() != "end_gcode")
        .map(|(key, value)| format!("; config.{key} = {value}"))
        .collect();
    lines.sort();
    lines
}

fn first_layer_xy_bounds(paths: &[Path]) -> Option<(f64, f64, f64, f64)> {
    let min_order = paths
        .iter()
        .filter_map(|path| path.segments.first())
        .map(|segment| segment.order)
        .fold(f64::INFINITY, f64::min);
    if !min_order.is_finite() {
        return None;
    }

    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    for path in paths {
        let is_first_layer = path
            .segments
            .first()
            .is_some_and(|segment| segment.order == min_order);
        if !is_first_layer {
            continue;
        }
        for point in &path.points {
            min_x = min_x.min(point.x);
            min_y = min_y.min(point.y);
            max_x = max_x.max(point.x);
            max_y = max_y.max(point.y);
        }
    }

    if min_x.is_finite() && min_y.is_finite() && max_x.is_finite() && max_y.is_finite() {
        Some((min_x, min_y, max_x, max_y))
    } else {
        None
    }
}

/// Render toolpaths to a Gcode program string.
///
/// Emits the full `config` as `; config.<field> = <value>` comment lines
/// immediately after the `; generated by manifold-core <version>` banner
/// (`<version>` is this crate's own `CARGO_PKG_VERSION`, i.e. the
/// workspace version -- see [`config_comment_lines`]) -- mirrors the common slicer convention of
/// embedding the slicing configuration in the Gcode file itself, so a
/// printed part's settings can be recovered from the file alone without
/// needing the original saved profile.
///
/// Prepends `config.start_gcode` (after the header comments) and appends
/// `config.end_gcode`, each with the `{print_min_x}`/`{print_min_y}`/
/// `{print_max_x}`/`{print_max_y}` placeholders substituted from the first
/// layer's XY bounding box (see `first_layer_xy_bounds`) -- `0.000` for all
/// four when `paths` is empty/has no segments, since there is no geometry
/// to bound. Either template is omitted entirely (no blank line) when set
/// to an empty string.
///
/// Inserts a tool-select line (`T{n}`) whenever consecutive paths are
/// assigned to different tools, followed by `G92 E0` to reset that tool's
/// filament position.
/// Explicitly emits `M83` (relative extrusion mode) immediately after
/// `start_gcode` (not before it -- `start_gcode` may itself change the
/// extrusion mode, so we can't assume it leaves the machine in relative
/// mode), and always before any extrusion moves, rather than relying on
/// the printer firmware's default: each extruding move's `E` value is
/// `Segment::extrusion_length` emitted as an incremental per-move delta
/// (see `toolpath::plan`, which finalizes `extrusion_length` from segment
/// geometry, line width, and the tool's `extrusion_multiplier`). Prime/purge
/// Gcode around tool changes is not implemented yet — follow-up work, see
/// ROADMAP.md Phase 2.
///
/// Emits `G10` (retract) immediately before the first move of a travel run
/// and `G11` (unretract) immediately before the first move resuming
/// extrusion, tracked as a per-tool `retracted` flag rather than emitted
/// unconditionally per move -- a run of consecutive travel or consecutive
/// extruding segments only ever gets one `G10`/`G11` at the transition.
/// `config.start_gcode` (e.g. `PRINT_START`) is assumed to already leave the
/// printer retracted, so `retracted` starts `true` -- both at the very
/// start of the program and again on every tool-select, matching a fresh
/// tool having no primed filament either. Firmware `G10`/`G11` retract
/// distance/speed (`M207`/`M208`) is assumed pre-configured on the printer
/// for now; no explicit distance/speed parameters are emitted -- follow-up
/// work if per-tool/per-config retract tuning is needed.
pub fn emit(paths: &[Path], config: &SlicerConfig) -> String {
    emit_with_machine(paths, config, None)
}

/// Render toolpaths to a Gcode program string, applying kinematic constraints
/// from `machine` when provided.
pub fn emit_with_machine(
    paths: &[Path],
    config: &SlicerConfig,
    machine: Option<&crate::machine::Machine>,
) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "; generated by manifold-core {}\n",
        env!("CARGO_PKG_VERSION")
    ));
    for line in config_comment_lines(config) {
        out.push_str(&line);
        out.push('\n');
    }
    let (min_x, min_y, max_x, max_y) = first_layer_xy_bounds(paths).unwrap_or((0.0, 0.0, 0.0, 0.0));
    let stats = crate::statistics::compute_print_statistics(paths, config, None);
    out.push_str(&format!("; estimated_time = {}\n", stats.formatted_time()));
    out.push_str(&format!(
        "; filament_used_m = {:.3}\n",
        stats.filament_length_meters
    ));
    out.push_str(&format!(
        "; filament_used_g = {:.2}\n",
        stats.filament_weight_grams
    ));
    out.push_str(&format!("; total_layers = {}\n", stats.total_layers));
    if !config.start_gcode.is_empty() {
        out.push_str(&interpolate(
            &config.start_gcode,
            min_x,
            min_y,
            max_x,
            max_y,
        ));
        out.push('\n');
    }

    // Explicitly set relative extrusion mode (M83) -- don't rely on the printer
    // firmware's default, since `emit`'s E values are always per-move deltas.
    // Emitted *after* `start_gcode` rather than before it: `start_gcode`
    // (e.g. a macro like `PRINT_START`) may itself change the extrusion mode,
    // so M83 must be the last word on extrusion mode before the first extruding move.
    out.push_str("M83\n");

    if let Some(pa) = config.pressure_advance {
        if pa > 0.0 {
            out.push_str(&format!("SET_PRESSURE_ADVANCE ADVANCE={pa:.4}\n"));
        }
    }

    let scv = config.square_corner_velocity();
    out.push_str(&format!(
        "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY={scv:.1}\n"
    ));

    let fan_pwm = (255.0 * (config.fan_speed_percent() / 100.0)).round() as u32;
    let overhang_fan_pwm = (255.0 * (config.overhang_fan_speed_percent() / 100.0)).round() as u32;
    let fan_delay = config.fan_layer_delay();
    let mut fan_is_on = false;
    let mut current_fan_pwm: Option<u32> = None;
    let mut seen_orders: Vec<f64> = Vec::new();

    if fan_delay > 0 {
        out.push_str("M106 S0\n");
        current_fan_pwm = Some(0);
    } else if fan_delay == 0 && fan_pwm > 0 {
        out.push_str(&format!("M106 S{fan_pwm}\n"));
        current_fan_pwm = Some(fan_pwm);
        fan_is_on = true;
    }

    let mut current_tool = None;
    let mut current_f: Option<f64> = None;
    let mut current_accel: Option<f64> = None;
    let mut last_move_kind: Option<MoveKind> = None;
    let mut retracted = true;
    let motion_model = config.resolved_motion_model(machine);
    let speed_deadband = config.speed_deadband_percent() / 100.0;
    let accel_deadband = config.acceleration_deadband_percent() / 100.0;

    let min_order = paths
        .iter()
        .filter_map(|path| path.segments.first())
        .map(|segment| segment.order)
        .fold(f64::INFINITY, f64::min);

    for path in paths {
        let path_order = path.segments.first().map(|s| s.order).unwrap_or(0.0);
        let is_first_layer = (path_order - min_order).abs() < 1e-4;
        if !seen_orders.iter().any(|&o| (o - path_order).abs() < 1e-4) {
            seen_orders.push(path_order);
            let layer_idx = (seen_orders.len() - 1) as u32;
            if !fan_is_on && layer_idx >= fan_delay {
                fan_is_on = true;
            }
        }
        if current_tool != Some(path.tool) {
            out.push_str(&format!("T{}\n", path.tool));
            out.push_str("G92 E0\n");
            current_tool = Some(path.tool);
            retracted = true;
        }

        let profiles = crate::kinematics::plan_path_velocities(
            &path.points,
            &path.segments,
            motion_model.as_ref(),
            is_first_layer,
            config.square_corner_velocity(),
        );

        let mut last_pos: Option<DVec3> = None;
        for (i, p) in path.points.iter().enumerate() {
            // `segments[i]` describes the edge `points[i] -> points[i + 1]`
            // (see `toolpath::Path`'s contract), so the move *arriving* at
            // `points[i]` (i >= 1) is `segments[i - 1]`, not `segments[i]`.
            // The very first point has no incoming edge in `path.segments` - it is
            // an inter-path positioning travel move (G0) from the previous position.
            let incoming_segment = if i > 0 {
                path.segments.get(i - 1)
            } else {
                None
            };
            let extruding =
                incoming_segment.is_some_and(|segment| segment.kind != MoveKind::Travel);
            let move_kind = incoming_segment.map_or(MoveKind::Travel, |s| s.kind);
            let move_speed = incoming_segment.map_or_else(
                || motion_model.max_feedrate(MoveKind::Travel, is_first_layer),
                |s| s.speed,
            );
            let actual_speed_mm_s = if i > 0 {
                profiles.get(i - 1).map_or(move_speed / 60.0, |prof| {
                    (prof.entry_speed.max(prof.cruise_speed).max(prof.exit_speed)) / 60.0
                })
            } else {
                move_speed / 60.0
            };

            // Skip zero-length moves to the exact same position
            if let Some(prev) = last_pos {
                if i > 0 && prev.distance(*p) < 1e-4 {
                    continue;
                }
            }

            // Update acceleration limit with deadband filtering
            let target_accel =
                motion_model.available_acceleration(move_kind, is_first_layer, actual_speed_mm_s);
            let should_emit_accel = current_accel.is_none_or(|active| {
                last_move_kind != Some(move_kind)
                    || (target_accel - active).abs() / active.max(1.0) >= accel_deadband
            });
            if should_emit_accel {
                out.push_str(&format!("SET_VELOCITY_LIMIT ACCEL={target_accel:.0}\n"));
                current_accel = Some(target_accel);
            }

            // Fan speed control
            let is_overhang_move = move_kind == MoveKind::Overhang || move_kind == MoveKind::Bridge;
            let target_fan_pwm = if is_overhang_move {
                overhang_fan_pwm
            } else if fan_is_on {
                fan_pwm
            } else {
                0
            };

            if current_fan_pwm != Some(target_fan_pwm) {
                out.push_str(&format!("M106 S{target_fan_pwm}\n"));
                current_fan_pwm = Some(target_fan_pwm);
            }

            // Retract before travel moves:
            // 1. If starting a new path (i == 0) and currently unretracted, retract before the G0 positioning move.
            // 2. If entering an in-path Travel segment, retract before the move.
            // Unretract before resuming an extruding move.
            if !extruding {
                if !retracted {
                    if config.use_firmware_retraction {
                        out.push_str("G10\n");
                    } else {
                        let r_len = config.retraction_length();
                        let r_spd = config.retraction_speed();
                        out.push_str(&format!("G1 E-{r_len:.5} F{r_spd:.0}\n"));
                        current_f = Some(r_spd);
                    }
                    retracted = true;
                }
            } else if retracted {
                if config.use_firmware_retraction {
                    out.push_str("G11\n");
                } else {
                    let u_len = config.retraction_length() + config.unretract_extra_length();
                    let u_spd = config.unretract_speed();
                    out.push_str(&format!("G1 E{u_len:.5} F{u_spd:.0}\n"));
                    current_f = Some(u_spd);
                }
                retracted = false;
            }

            let cmd = if !extruding { "G0" } else { "G1" };
            out.push_str(&format!("{cmd} X{:.3} Y{:.3} Z{:.3}", p.x, p.y, p.z));
            if extruding {
                let delta_e = incoming_segment.map_or(0.0, |segment| segment.extrusion_length);
                out.push_str(&format!(" E{delta_e:.5}"));
            }

            let should_emit_f = current_f.is_none_or(|active| {
                last_move_kind != Some(move_kind)
                    || (move_speed - active).abs() / active.max(1.0) >= speed_deadband
            });
            if should_emit_f {
                out.push_str(&format!(" F{move_speed:.3}"));
                current_f = Some(move_speed);
            }
            out.push('\n');
            last_pos = Some(*p);
            last_move_kind = Some(move_kind);
        }
    }

    if !retracted {
        if config.use_firmware_retraction {
            out.push_str("G10\n");
        } else {
            let r_len = config.retraction_length();
            let r_spd = config.retraction_speed();
            out.push_str(&format!("G1 E-{r_len:.5} F{r_spd:.0}\n"));
        }
    }

    if !config.end_gcode.is_empty() {
        out.push_str(&interpolate(&config.end_gcode, min_x, min_y, max_x, max_y));
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::ToolId;

    /// `SlicerConfig::default()` with blank start/end gcode templates, so
    /// tests that only care about tool-change/E-axis/command behavior
    /// aren't perturbed by the default `PRINT_START`/`PRINT_END` lines.
    fn config_without_print_gcode() -> SlicerConfig {
        SlicerConfig {
            start_gcode: String::new(),
            end_gcode: String::new(),
            use_firmware_retraction: true,
            ..SlicerConfig::default()
        }
    }

    #[test]
    fn emit_inserts_tool_change_between_differing_tools() {
        let paths = vec![
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(0),
            },
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(1),
            },
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(1),
            },
        ];

        let out = emit(&paths, &config_without_print_gcode());

        assert_eq!(out.matches("T0\n").count(), 1);
        assert_eq!(out.matches("T1\n").count(), 1);
    }

    #[test]
    fn emit_omits_tool_line_when_no_paths() {
        let out = emit(&[], &config_without_print_gcode());
        assert!(!out.lines().any(|l| l.starts_with('T')));
    }

    #[test]
    fn emit_derives_g0_g1_from_segment_kind() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // A single path: first point is always the travel move (G0).
        // `segments[i]` describes the edge `points[i] -> points[i + 1]`, so
        // the move arriving at `points[1]` is governed by `segments[0]`
        // (WallOuter -> G1) and the move arriving at `points[2]` is
        // governed by `segments[1]` (Travel -> G0) — proving the command
        // derives from the *incoming* segment's kind rather than position
        // alone.
        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());
        let commands: Vec<&str> = out
            .lines()
            .filter(|line| line.starts_with("G0 ") || line.starts_with("G1 "))
            .map(|line| &line[..2])
            .collect();

        assert_eq!(commands, vec!["G0", "G1", "G0"]);
    }

    #[test]
    fn emit_emits_explicit_retractions_when_firmware_retraction_is_disabled() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
                DVec3::new(3.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let config = SlicerConfig {
            use_firmware_retraction: false,
            retraction_length: Some(0.8),
            retraction_speed: Some(3000.0),
            unretract_speed: Some(3000.0),
            unretract_extra_length: Some(0.1),
            start_gcode: String::new(),
            end_gcode: String::new(),
            ..SlicerConfig::default()
        };

        let out = emit(&paths, &config);

        // Explicit unretract with extra length before first extrusion: E0.90000
        assert!(out.contains("G1 E0.90000 F3000"));
        // Explicit retract before travel: E-0.80000
        assert!(out.contains("G1 E-0.80000 F3000"));
        assert!(!out.contains("G10"));
        assert!(!out.contains("G11"));
    }

    #[test]
    fn emit_retracts_before_travel_and_unretracts_before_resuming_extrusion() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // Extrude -> travel -> extrude: expect exactly one G10 (before the
        // travel move) and one G11 (before extrusion resumes), each on its
        // own line ahead of the corresponding G0/G1.
        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
                DVec3::new(3.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        // Started retracted (fresh tool), so the *first* extruding move
        // (arriving at points[1]) must be preceded by an unretract.
        let out = emit(&paths, &config_without_print_gcode());
        let lines: Vec<&str> = out.lines().collect();
        let g10_idx = lines.iter().position(|l| *l == "G10");
        let g11_idx = lines.iter().position(|l| *l == "G11");
        assert_eq!(
            out.matches("G10").count(),
            2,
            "one before travel, one at end of program"
        );
        assert_eq!(
            out.matches("G11").count(),
            2,
            "one before the first extruding move, one after the travel"
        );

        let g0_travel_idx = lines
            .iter()
            .position(|l| l.starts_with("G0 X2.000"))
            .expect("travel move to points[2]");
        let g1_first_idx = lines
            .iter()
            .position(|l| l.starts_with("G1 X1.000"))
            .expect("first extruding move to points[1]");
        let g1_second_idx = lines
            .iter()
            .position(|l| l.starts_with("G1 X3.000"))
            .expect("second extruding move to points[3]");

        // G11 immediately precedes the first extruding move.
        assert_eq!(lines[g1_first_idx - 1], "G11");
        // G10 immediately precedes the travel move.
        assert_eq!(lines[g0_travel_idx - 1], "G10");
        assert_eq!(g10_idx.unwrap(), g0_travel_idx - 1);
        // G11 immediately precedes the second extruding move (resuming after
        // travel).
        assert_eq!(lines[g1_second_idx - 1], "G11");
        assert_eq!(g11_idx.unwrap(), g1_first_idx - 1);
    }

    #[test]
    fn emit_does_not_repeat_retract_or_unretract_across_consecutive_same_kind_segments() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // Two consecutive travel segments followed by two consecutive
        // extruding segments: only one G10 (at the first travel) and one
        // G11 (at the first resumed extrusion) should be emitted, not one
        // per segment.
        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
                DVec3::new(3.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());
        // Already retracted from the start, so the leading travel run
        // triggers no G10 at all; only the later switch to extrusion emits
        // one G11, followed by a final G10 retract at program completion.
        assert_eq!(
            out.matches("G10").count(),
            1,
            "final retract at end of program"
        );
        assert_eq!(out.matches("G11").count(), 1);
    }

    #[test]
    fn emit_resets_retracted_state_on_tool_change() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // First tool ends up unretracted (mid-extrusion) when the path
        // ends; the tool change to a fresh tool must not carry that state
        // over, so the new tool's first extruding move still gets its own
        // G11 rather than assuming it's already unretracted.
        let paths = vec![
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                }],
                tool: ToolId(1),
            },
        ];

        let out = emit(&paths, &config_without_print_gcode());
        assert_eq!(
            out.matches("G11").count(),
            2,
            "each tool's first extruding move gets its own unretract"
        );
        assert_eq!(
            out.matches("G10").count(),
            1,
            "final retract at end of program"
        );
    }

    #[test]
    fn emit_emits_incremental_e_for_extruding_segments_and_omits_it_for_travel() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
                DVec3::new(3.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 1.5,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    extrusion_length: 0.0,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 2.5,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());
        let move_lines: Vec<&str> = out
            .lines()
            .filter(|line| line.starts_with("G0 ") || line.starts_with("G1 "))
            .collect();

        // The four point-moves, in order:
        // First point: plain travel, no E.
        assert!(move_lines[0].starts_with("G0") && !move_lines[0].contains('E'));
        // Second point: extruding move, E is the incremental delta (1.5).
        assert!(move_lines[1].starts_with("G1") && move_lines[1].contains("E1.50000"));
        // Third point: Travel segment, no E.
        assert!(move_lines[2].starts_with("G0") && !move_lines[2].contains('E'));
        // Fourth point: extruding move, E is the incremental delta for this segment (2.5).
        assert!(move_lines[3].starts_with("G1") && move_lines[3].contains("E2.50000"));
    }

    #[test]
    fn emit_resets_e_to_zero_on_tool_change() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 5.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 1.0,
                    ..Segment::default()
                }],
                tool: ToolId(1),
            },
        ];

        let out = emit(&paths, &config_without_print_gcode());

        assert_eq!(out.matches("G92 E0").count(), 2);
        assert!(out.contains("E5.00000"));
        // The second tool's extrusion starts fresh from zero rather than
        // continuing tool 0's running total of 5.0.
        assert!(out.contains("E1.00000"));
        assert!(!out.contains("E6.00000"));
    }

    #[test]
    fn emit_writes_m83_before_any_extrusion_move() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![Path {
            points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
            segments: vec![Segment {
                kind: MoveKind::WallOuter,
                extrusion_length: 1.0,
                ..Segment::default()
            }],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());

        let m83_pos = out.find("M83").expect("M83 must be emitted");
        let first_extruding_move_pos = out.find("G1").expect("an extruding move must be emitted");
        assert!(m83_pos < first_extruding_move_pos);
    }

    #[test]
    fn emit_writes_klipper_set_velocity_limit_when_acceleration_changes() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 1.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
            Path {
                points: vec![DVec3::new(1.0, 0.0, 0.0), DVec3::new(2.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::Travel,
                    extrusion_length: 0.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
        ];

        let config = SlicerConfig {
            first_layer_acceleration: Some(2500.0),
            outer_wall_acceleration: Some(2500.0),
            travel_acceleration: Some(10000.0),
            pressure_advance: Some(0.04),
            ..config_without_print_gcode()
        };

        let out = emit(&paths, &config);

        assert!(out.contains("SET_PRESSURE_ADVANCE ADVANCE=0.0400"));
        assert!(out.contains("SET_VELOCITY_LIMIT ACCEL=2500"));
        assert!(out.contains("SET_VELOCITY_LIMIT ACCEL=10000"));
    }

    #[test]
    fn emit_writes_config_fields_as_comments_before_m83() {
        let config = SlicerConfig {
            layer_height: 0.24,
            nozzle_diameter: 0.5,
            ..config_without_print_gcode()
        };

        let out = emit(&[], &config);

        let layer_height_pos = out
            .find("; config.layer_height = 0.24")
            .expect("layer_height must be emitted as a config comment");
        let nozzle_diameter_pos = out
            .find("; config.nozzle_diameter = 0.5")
            .expect("nozzle_diameter must be emitted as a config comment");
        let m83_pos = out.find("M83").expect("M83 must be emitted");
        assert!(layer_height_pos < m83_pos);
        assert!(nozzle_diameter_pos < m83_pos);

        // start_gcode/end_gcode are deliberately not echoed as config
        // comments -- they're already emitted verbatim as their own
        // Gcode blocks, so repeating them here would be redundant.
        assert!(!out.contains("config.start_gcode"));
        assert!(!out.contains("config.end_gcode"));
    }

    #[test]
    fn interpolate_substitutes_all_four_bounding_box_placeholders() {
        let template =
            "PRINT_MIN={print_min_x},{print_min_y} PRINT_MAX={print_max_x},{print_max_y}";
        let out = interpolate(template, 1.0, 2.5, 10.0, 20.25);
        assert_eq!(out, "PRINT_MIN=1.000,2.500 PRINT_MAX=10.000,20.250");
    }

    #[test]
    fn interpolate_leaves_unrelated_braces_untouched() {
        let out = interpolate("T_TOOL=240 T_BED=105", 0.0, 0.0, 0.0, 0.0);
        assert_eq!(out, "T_TOOL=240 T_BED=105");
    }

    #[test]
    fn emit_substitutes_first_layer_bounding_box_into_start_gcode() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // Two "layers" (distinguished by `Segment::order`): layer 0 spans
        // a 10x10 square, layer 1 (order 1.0, printed after) spans a wider
        // 20x20 square. The bounding box substituted into start_gcode must
        // reflect only the *first* layer (order 0.0), proving the bounds
        // are derived from `Segment::order` rather than from every point in
        // `paths`.
        let paths = vec![
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(10.0, 10.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    order: 0.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
            Path {
                points: vec![DVec3::new(-5.0, -5.0, 0.25), DVec3::new(20.0, 20.0, 0.25)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    order: 1.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
        ];
        let config = SlicerConfig {
            start_gcode: "PRINT_START PRINT_MIN={print_min_x},{print_min_y} PRINT_MAX={print_max_x},{print_max_y}"
                .to_string(),
            end_gcode: "PRINT_END".to_string(),
            ..SlicerConfig::default()
        };

        let out = emit(&paths, &config);

        assert!(out.contains("PRINT_START PRINT_MIN=0.000,0.000 PRINT_MAX=10.000,10.000"));
        assert!(out.trim_end().ends_with("PRINT_END"));
    }

    #[test]
    fn emit_writes_f_reflecting_segment_speed_and_omits_it_when_unchanged() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // Three consecutive incoming segments: the first two share a speed
        // (F should only be emitted once, on the first), the third has a
        // different speed (F should be emitted again).
        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
                DVec3::new(3.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    speed: 3000.0,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    speed: 3000.0,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    speed: 9000.0,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());
        let move_lines: Vec<&str> = out
            .lines()
            .filter(|line| line.starts_with("G0 ") || line.starts_with("G1 "))
            .collect();

        // First move (i == 0) is a positioning travel move, so it carries
        // the travel speed F9000.
        assert!(move_lines[0].contains("F9000.000"));
        // Second move's incoming segment (speed 3000.0) has a different speed from
        // the prior emitted F9000, so F3000 is emitted.
        assert!(move_lines[1].contains("F3000.000"));
        // Third move's incoming segment shares the same speed (3000.0) as
        // the previous emitted F, so F must be omitted entirely.
        assert!(!move_lines[2].contains('F'));
        // Fourth move's incoming segment has a different speed (9000.0), so
        // F is emitted again.
        assert!(move_lines[3].contains("F9000.000"));
    }

    #[test]
    fn emit_substitutes_zero_bounds_when_paths_have_no_segments() {
        let config = SlicerConfig {
            start_gcode: "PRINT_START PRINT_MIN={print_min_x},{print_min_y}".to_string(),
            ..SlicerConfig::default()
        };

        let out = emit(&[], &config);

        assert!(out.contains("PRINT_START PRINT_MIN=0.000,0.000"));
    }

    #[test]
    fn emit_disables_fan_on_first_layer_and_enables_it_at_configured_layer_delay() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let path0 = Path {
            points: vec![DVec3::new(0.0, 0.0, 0.2), DVec3::new(10.0, 0.0, 0.2)],
            segments: vec![Segment {
                kind: MoveKind::WallOuter,
                order: 0.2,
                ..Segment::default()
            }],
            tool: ToolId(0),
        };
        let path1 = Path {
            points: vec![DVec3::new(0.0, 0.0, 0.4), DVec3::new(10.0, 0.0, 0.4)],
            segments: vec![Segment {
                kind: MoveKind::WallOuter,
                order: 0.4,
                ..Segment::default()
            }],
            tool: ToolId(0),
        };

        let config = SlicerConfig {
            fan_speed_percent: Some(100.0),
            fan_layer_delay: Some(1),
            ..config_without_print_gcode()
        };

        let out = emit(&[path0, path1], &config);
        assert!(out.contains("M106 S0\n"), "must turn off fan at start");
        assert!(out.contains("M106 S255\n"), "must turn on fan at layer 1");
    }

    #[test]
    fn emit_sets_overhang_fan_speed_for_overhang_moves_and_restores_normal() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let path = Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.4),
                DVec3::new(10.0, 0.0, 0.4),
                DVec3::new(20.0, 0.0, 0.4),
                DVec3::new(30.0, 0.0, 0.4),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    order: 0.4,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Overhang,
                    order: 0.4,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    order: 0.4,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        };

        let config = SlicerConfig {
            fan_speed_percent: Some(50.0),           // PWM ~ 128
            overhang_fan_speed_percent: Some(100.0), // PWM = 255
            fan_layer_delay: Some(0),
            ..SlicerConfig::default()
        };

        let out = emit(&[path], &config);

        assert!(out.contains("M106 S128\n"), "must set 50% fan initially");
        assert!(
            out.contains("M106 S255\n"),
            "must ramp to 100% fan on overhang move"
        );
    }

    #[test]
    fn emit_sets_travel_feedrate_and_acceleration_on_inter_path_travel_moves() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let path1 = Path {
            points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(10.0, 0.0, 0.0)],
            segments: vec![Segment {
                kind: MoveKind::WallOuter,
                extrusion_length: 0.5,
                speed: 3000.0,
                ..Segment::default()
            }],
            tool: ToolId(0),
        };
        let path2 = Path {
            points: vec![DVec3::new(50.0, 50.0, 0.0), DVec3::new(60.0, 50.0, 0.0)],
            segments: vec![Segment {
                kind: MoveKind::WallOuter,
                extrusion_length: 0.5,
                speed: 3000.0,
                ..Segment::default()
            }],
            tool: ToolId(0),
        };

        let config = SlicerConfig {
            use_firmware_retraction: false,
            travel_speed: 12000.0,
            retraction_speed: Some(900.0),
            retraction_length: Some(0.5),
            travel_acceleration: Some(8000.0),
            outer_wall_acceleration: Some(2000.0),
            ..config_without_print_gcode()
        };

        let out = emit(&[path1, path2], &config);

        // Retraction happens at 900 mm/min
        assert!(out.contains("G1 E-0.50000 F900\n"));
        // Inter-path travel move to (50, 50, 0) must set travel acceleration and travel speed F12000
        assert!(out.contains("SET_VELOCITY_LIMIT ACCEL=8000\n"));
        assert!(out.contains("G0 X50.000 Y50.000 Z0.000 F12000.000\n"));
    }

    #[test]
    fn emit_omits_zero_length_non_extruding_moves_and_zero_delta_e() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let path = Path {
            points: vec![
                DVec3::new(10.0, 10.0, 0.2),
                DVec3::new(10.0, 10.0, 0.2), // duplicate zero-length point
                DVec3::new(20.0, 10.0, 0.2),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 0.0, // zero extrusion
                    speed: 3000.0,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 0.5,
                    speed: 3000.0,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        };

        let config = config_without_print_gcode();
        let out = emit(&[path], &config);

        // Never emit E0.00000
        assert!(!out.contains("E0.00000"));
        // Never emit duplicate move to (10, 10, 0.2)
        let count_p0 = out.matches("X10.000 Y10.000").count();
        assert_eq!(
            count_p0, 1,
            "only the initial G0 positioning move is emitted"
        );
    }

    #[test]
    fn emit_emits_klipper_square_corner_velocity_in_header() {
        let config = SlicerConfig {
            square_corner_velocity: Some(8.5),
            ..config_without_print_gcode()
        };

        let out = emit(&[], &config);

        assert!(out.contains("SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=8.5\n"));
    }

    #[test]
    fn emit_applies_deadband_to_acceleration_commands() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let path = Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(10.0, 0.0, 0.0),
                DVec3::new(20.0, 0.0, 0.0),
                DVec3::new(30.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 0.5,
                    speed: 3000.0,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 0.5,
                    speed: 3100.0, // minor speed variation (~3%)
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 0.5,
                    speed: 3050.0,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        };

        let config = SlicerConfig {
            outer_wall_acceleration: Some(2500.0),
            first_layer_acceleration: Some(2500.0),
            acceleration_deadband_percent: Some(20.0),
            ..config_without_print_gcode()
        };

        let out = emit(&[path], &config);

        // Only one SET_VELOCITY_LIMIT ACCEL=2500 for the outer wall pass, not 3
        let accel_count = out.matches("SET_VELOCITY_LIMIT ACCEL=2500").count();
        assert_eq!(accel_count, 1);
    }
}
