//! Gcode emission from planned toolpaths.

use crate::{
    toolpath::{MoveKind, Path},
    SlicerConfig,
};

/// Render toolpaths to a Gcode program string.
///
/// Inserts a tool-select line (`T{n}`) whenever consecutive paths are
/// assigned to different tools. Prime/purge Gcode around tool changes is
/// not implemented yet — follow-up work, see ROADMAP.md Phase 2.
pub fn emit(paths: &[Path], config: &SlicerConfig) -> String {
    let mut out = String::new();
    out.push_str("; generated by manifold-core\n");
    out.push_str(&format!("; layer_height={}\n", config.layer_height));

    let mut current_tool = None;

    for path in paths {
        if current_tool != Some(path.tool) {
            out.push_str(&format!("T{}\n", path.tool));
            current_tool = Some(path.tool);
        }

        for (i, p) in path.points.iter().enumerate() {
            // `segments[i]` describes the edge `points[i] -> points[i + 1]`
            // (see `toolpath::Path`'s contract), so the move *arriving* at
            // `points[i]` (i >= 1) is `segments[i - 1]`, not `segments[i]`.
            // The very first point has no incoming edge - it's always a
            // plain positioning move (G0).
            let extruding = i > 0
                && path
                    .segments
                    .get(i - 1)
                    .is_some_and(|segment| segment.kind != MoveKind::Travel);
            let cmd = if i == 0 || !extruding { "G0" } else { "G1" };
            out.push_str(&format!("{cmd} X{:.3} Y{:.3} Z{:.3}\n", p.x, p.y, p.z));
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::ToolId;

    #[test]
    fn emit_inserts_tool_change_between_differing_tools() {
        let paths = vec![
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(0),
            },
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(1),
            },
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(1),
            },
        ];

        let out = emit(&paths, &SlicerConfig::default());

        assert_eq!(out.matches("T0\n").count(), 1);
        assert_eq!(out.matches("T1\n").count(), 1);
    }

    #[test]
    fn emit_omits_tool_line_when_no_paths() {
        let out = emit(&[], &SlicerConfig::default());
        assert!(!out.contains('T'));
    }

    #[test]
    fn emit_derives_g0_g1_from_segment_kind() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // A single path: first point is always the travel move (G0).
        // `segments[i]` describes the edge `points[i] -> points[i + 1]`, so
        // the move arriving at `points[1]` is governed by `segments[0]`
        // (WallOuter -> G1) and the move arriving at `points[2]` is
        // governed by `segments[1]` (Travel -> G0) — proving the command
        // derives from the *incoming* segment's kind rather than position
        // alone.
        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &SlicerConfig::default());
        let commands: Vec<&str> = out
            .lines()
            .filter(|line| line.starts_with("G0") || line.starts_with("G1"))
            .map(|line| &line[..2])
            .collect();

        assert_eq!(commands, vec!["G0", "G1", "G0"]);
    }
}
