//! Gcode emission from planned toolpaths.

use crate::{
    toolpath::{MoveKind, Path},
    SlicerConfig,
};

/// Substitute `{print_min_x}`, `{print_min_y}`, `{print_max_x}`,
/// `{print_max_y}` placeholders in a Gcode template with the given first-
/// layer XY bounding box, formatted to 3 decimal places (matching the
/// coordinate precision `emit` uses for move lines). Any other `{...}`
/// text in the template (e.g. a Klipper macro's other named parameters
/// like `T_TOOL=240`) is left untouched -- this only recognizes the four
/// bounding-box tokens above.
fn interpolate(template: &str, min_x: f64, min_y: f64, max_x: f64, max_y: f64) -> String {
    template
        .replace("{print_min_x}", &format!("{min_x:.3}"))
        .replace("{print_min_y}", &format!("{min_y:.3}"))
        .replace("{print_max_x}", &format!("{max_x:.3}"))
        .replace("{print_max_y}", &format!("{max_y:.3}"))
}

/// XY bounding box of the first printed layer, identified by the minimum
/// `Segment::order` value across all paths -- robust to non-planar order
/// fields, where Z alone doesn't reliably identify "layer 1" (unlike a
/// flat `Height` field, a curved layer's points don't share one Z value,
/// but every segment sliced from it still shares the same source layer's
/// `order`, copied verbatim by `toolpath::plan`). Returns `None` when
/// `paths` has no segments at all (nothing to bound).
fn first_layer_xy_bounds(paths: &[Path]) -> Option<(f64, f64, f64, f64)> {
    let min_order = paths
        .iter()
        .filter_map(|path| path.segments.first())
        .map(|segment| segment.order)
        .fold(f64::INFINITY, f64::min);
    if !min_order.is_finite() {
        return None;
    }

    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    for path in paths {
        let is_first_layer = path
            .segments
            .first()
            .is_some_and(|segment| segment.order == min_order);
        if !is_first_layer {
            continue;
        }
        for point in &path.points {
            min_x = min_x.min(point.x);
            min_y = min_y.min(point.y);
            max_x = max_x.max(point.x);
            max_y = max_y.max(point.y);
        }
    }

    if min_x.is_finite() && min_y.is_finite() && max_x.is_finite() && max_y.is_finite() {
        Some((min_x, min_y, max_x, max_y))
    } else {
        None
    }
}

/// Render toolpaths to a Gcode program string.
///
/// Prepends `config.start_gcode` (after the header comments) and appends
/// `config.end_gcode`, each with the `{print_min_x}`/`{print_min_y}`/
/// `{print_max_x}`/`{print_max_y}` placeholders substituted from the first
/// layer's XY bounding box (see `first_layer_xy_bounds`) -- `0.000` for all
/// four when `paths` is empty/has no segments, since there is no geometry
/// to bound. Either template is omitted entirely (no blank line) when set
/// to an empty string.
///
/// Inserts a tool-select line (`T{n}`) whenever consecutive paths are
/// assigned to different tools, followed by `G92 E0` to reset that tool's
/// filament position — each tool is tracked as its own independent
/// extruder, so a fresh tool-select always restarts extrusion accounting
/// from zero rather than carrying over the previous tool's total. Uses
/// absolute extrusion mode (`M82`, the common firmware default): each
/// extruding move's `E` value is `Segment::extrusion_length` accumulated
/// onto a running per-tool total (see `toolpath::plan`, which finalizes
/// `extrusion_length` from segment geometry, line width, and the tool's
/// `extrusion_multiplier`), not emitted as a per-move delta. Prime/purge
/// Gcode around tool changes is not implemented yet — follow-up work, see
/// ROADMAP.md Phase 2.
pub fn emit(paths: &[Path], config: &SlicerConfig) -> String {
    let mut out = String::new();
    out.push_str("; generated by manifold-core\n");
    out.push_str(&format!("; layer_height={}\n", config.layer_height));

    let (min_x, min_y, max_x, max_y) = first_layer_xy_bounds(paths).unwrap_or((0.0, 0.0, 0.0, 0.0));
    if !config.start_gcode.is_empty() {
        out.push_str(&interpolate(
            &config.start_gcode,
            min_x,
            min_y,
            max_x,
            max_y,
        ));
        out.push('\n');
    }

    let mut current_tool = None;
    let mut current_e = 0.0;

    for path in paths {
        if current_tool != Some(path.tool) {
            out.push_str(&format!("T{}\n", path.tool));
            out.push_str("G92 E0\n");
            current_tool = Some(path.tool);
            current_e = 0.0;
        }

        for (i, p) in path.points.iter().enumerate() {
            // `segments[i]` describes the edge `points[i] -> points[i + 1]`
            // (see `toolpath::Path`'s contract), so the move *arriving* at
            // `points[i]` (i >= 1) is `segments[i - 1]`, not `segments[i]`.
            // The very first point has no incoming edge - it's always a
            // plain positioning move (G0).
            let incoming_segment = if i > 0 {
                path.segments.get(i - 1)
            } else {
                None
            };
            let extruding =
                incoming_segment.is_some_and(|segment| segment.kind != MoveKind::Travel);
            let cmd = if i == 0 || !extruding { "G0" } else { "G1" };
            out.push_str(&format!("{cmd} X{:.3} Y{:.3} Z{:.3}", p.x, p.y, p.z));
            if extruding {
                current_e += incoming_segment.map_or(0.0, |segment| segment.extrusion_length);
                out.push_str(&format!(" E{current_e:.5}"));
            }
            out.push('\n');
        }
    }

    if !config.end_gcode.is_empty() {
        out.push_str(&interpolate(&config.end_gcode, min_x, min_y, max_x, max_y));
        out.push('\n');
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ids::ToolId;

    /// `SlicerConfig::default()` with blank start/end gcode templates, so
    /// tests that only care about tool-change/E-axis/command behavior
    /// aren't perturbed by the default `PRINT_START`/`PRINT_END` lines.
    fn config_without_print_gcode() -> SlicerConfig {
        SlicerConfig {
            start_gcode: String::new(),
            end_gcode: String::new(),
            ..SlicerConfig::default()
        }
    }

    #[test]
    fn emit_inserts_tool_change_between_differing_tools() {
        let paths = vec![
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(0),
            },
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(1),
            },
            Path {
                points: Vec::new(),
                segments: Vec::new(),
                tool: ToolId(1),
            },
        ];

        let out = emit(&paths, &config_without_print_gcode());

        assert_eq!(out.matches("T0\n").count(), 1);
        assert_eq!(out.matches("T1\n").count(), 1);
    }

    #[test]
    fn emit_omits_tool_line_when_no_paths() {
        let out = emit(&[], &config_without_print_gcode());
        assert!(!out.contains('T'));
    }

    #[test]
    fn emit_derives_g0_g1_from_segment_kind() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // A single path: first point is always the travel move (G0).
        // `segments[i]` describes the edge `points[i] -> points[i + 1]`, so
        // the move arriving at `points[1]` is governed by `segments[0]`
        // (WallOuter -> G1) and the move arriving at `points[2]` is
        // governed by `segments[1]` (Travel -> G0) — proving the command
        // derives from the *incoming* segment's kind rather than position
        // alone.
        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());
        let commands: Vec<&str> = out
            .lines()
            .filter(|line| line.starts_with("G0") || line.starts_with("G1"))
            .map(|line| &line[..2])
            .collect();

        assert_eq!(commands, vec!["G0", "G1", "G0"]);
    }

    #[test]
    fn emit_accumulates_absolute_e_across_extruding_segments_and_omits_it_for_travel() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![Path {
            points: vec![
                DVec3::new(0.0, 0.0, 0.0),
                DVec3::new(1.0, 0.0, 0.0),
                DVec3::new(2.0, 0.0, 0.0),
            ],
            segments: vec![
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 1.5,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::Travel,
                    extrusion_length: 0.0,
                    ..Segment::default()
                },
                Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 2.5,
                    ..Segment::default()
                },
            ],
            tool: ToolId(0),
        }];

        let out = emit(&paths, &config_without_print_gcode());
        let lines: Vec<&str> = out.lines().collect();

        // lines[0..=1] are header comments (start/end gcode is blank in
        // this test's config), lines[2] is "T0", lines[3] is "G92 E0"; the
        // three point-moves follow at lines[4..=6].
        // First point: plain travel, no E.
        assert!(lines[4].starts_with("G0") && !lines[4].contains('E'));
        // Second point: extruding move, E accumulates the first segment's
        // extrusion_length (1.5).
        assert!(lines[5].starts_with("G1") && lines[5].contains("E1.50000"));
        // Third point: a Travel segment interrupted extrusion, so this move
        // is G0 and carries no E, but the running total is preserved for
        // the *next* extruding move rather than reset.
        assert!(lines[6].starts_with("G0") && !lines[6].contains('E'));
    }

    #[test]
    fn emit_resets_e_to_zero_on_tool_change() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        let paths = vec![
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 5.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(1.0, 0.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    extrusion_length: 1.0,
                    ..Segment::default()
                }],
                tool: ToolId(1),
            },
        ];

        let out = emit(&paths, &config_without_print_gcode());

        assert_eq!(out.matches("G92 E0").count(), 2);
        assert!(out.contains("E5.00000"));
        // The second tool's extrusion starts fresh from zero rather than
        // continuing tool 0's running total of 5.0.
        assert!(out.contains("E1.00000"));
        assert!(!out.contains("E6.00000"));
    }

    #[test]
    fn interpolate_substitutes_all_four_bounding_box_placeholders() {
        let template =
            "PRINT_MIN={print_min_x},{print_min_y} PRINT_MAX={print_max_x},{print_max_y}";
        let out = interpolate(template, 1.0, 2.5, 10.0, 20.25);
        assert_eq!(out, "PRINT_MIN=1.000,2.500 PRINT_MAX=10.000,20.250");
    }

    #[test]
    fn interpolate_leaves_unrelated_braces_untouched() {
        let out = interpolate("T_TOOL=240 T_BED=105", 0.0, 0.0, 0.0, 0.0);
        assert_eq!(out, "T_TOOL=240 T_BED=105");
    }

    #[test]
    fn emit_substitutes_first_layer_bounding_box_into_start_gcode() {
        use crate::toolpath::Segment;
        use glam::DVec3;

        // Two "layers" (distinguished by `Segment::order`): layer 0 spans
        // a 10x10 square, layer 1 (order 1.0, printed after) spans a wider
        // 20x20 square. The bounding box substituted into start_gcode must
        // reflect only the *first* layer (order 0.0), proving the bounds
        // are derived from `Segment::order` rather than from every point in
        // `paths`.
        let paths = vec![
            Path {
                points: vec![DVec3::new(0.0, 0.0, 0.0), DVec3::new(10.0, 10.0, 0.0)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    order: 0.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
            Path {
                points: vec![DVec3::new(-5.0, -5.0, 0.25), DVec3::new(20.0, 20.0, 0.25)],
                segments: vec![Segment {
                    kind: MoveKind::WallOuter,
                    order: 1.0,
                    ..Segment::default()
                }],
                tool: ToolId(0),
            },
        ];
        let config = SlicerConfig {
            start_gcode: "PRINT_START PRINT_MIN={print_min_x},{print_min_y} PRINT_MAX={print_max_x},{print_max_y}"
                .to_string(),
            end_gcode: "PRINT_END".to_string(),
            ..SlicerConfig::default()
        };

        let out = emit(&paths, &config);

        assert!(out.contains("PRINT_START PRINT_MIN=0.000,0.000 PRINT_MAX=10.000,10.000"));
        assert!(out.trim_end().ends_with("PRINT_END"));
    }

    #[test]
    fn emit_substitutes_zero_bounds_when_paths_have_no_segments() {
        let config = SlicerConfig {
            start_gcode: "PRINT_START PRINT_MIN={print_min_x},{print_min_y}".to_string(),
            ..SlicerConfig::default()
        };

        let out = emit(&[], &config);

        assert!(out.contains("PRINT_START PRINT_MIN=0.000,0.000"));
    }
}
